//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERS_Client_Console.RemoteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Email", Namespace="http://schemas.datacontract.org/2004/07/Email_Registration_Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERS_Client_Console.RemoteService.EmailFull))]
    public partial class Email : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_reg {
            get {
                return this.date_regField;
            }
            set {
                if ((this.date_regField.Equals(value) != true)) {
                    this.date_regField = value;
                    this.RaisePropertyChanged("date_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string from {
            get {
                return this.fromField;
            }
            set {
                if ((object.ReferenceEquals(this.fromField, value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                if ((object.ReferenceEquals(this.subjectField, value) != true)) {
                    this.subjectField = value;
                    this.RaisePropertyChanged("subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string to {
            get {
                return this.toField;
            }
            set {
                if ((object.ReferenceEquals(this.toField, value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailFull", Namespace="http://schemas.datacontract.org/2004/07/Email_Registration_Service")]
    [System.SerializableAttribute()]
    public partial class EmailFull : ERS_Client_Console.RemoteService.Email {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] tagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] tags {
            get {
                return this.tagsField;
            }
            set {
                if ((object.ReferenceEquals(this.tagsField, value) != true)) {
                    this.tagsField = value;
                    this.RaisePropertyChanged("tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteService.IEmailRegistration")]
    public interface IEmailRegistration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/TestConnection", ReplyAction="http://tempuri.org/IEmailRegistration/TestConnectionResponse")]
        bool TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/GetEmails", ReplyAction="http://tempuri.org/IEmailRegistration/GetEmailsResponse")]
        ERS_Client_Console.RemoteService.Email[] GetEmails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/GetEmailById", ReplyAction="http://tempuri.org/IEmailRegistration/GetEmailByIdResponse")]
        ERS_Client_Console.RemoteService.EmailFull GetEmailById(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/AddEmail", ReplyAction="http://tempuri.org/IEmailRegistration/AddEmailResponse")]
        void AddEmail(ERS_Client_Console.RemoteService.EmailFull email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/UpdateEmail", ReplyAction="http://tempuri.org/IEmailRegistration/UpdateEmailResponse")]
        void UpdateEmail(ERS_Client_Console.RemoteService.EmailFull email, string[] unrelatedTags);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/GetEmailsByPeriod", ReplyAction="http://tempuri.org/IEmailRegistration/GetEmailsByPeriodResponse")]
        ERS_Client_Console.RemoteService.Email[] GetEmailsByPeriod(System.DateTime date_left, System.DateTime date_right);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/GetEmailsByTo", ReplyAction="http://tempuri.org/IEmailRegistration/GetEmailsByToResponse")]
        ERS_Client_Console.RemoteService.Email[] GetEmailsByTo(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/GetEmailsByFrom", ReplyAction="http://tempuri.org/IEmailRegistration/GetEmailsByFromResponse")]
        ERS_Client_Console.RemoteService.Email[] GetEmailsByFrom(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailRegistration/GetEmailsByTag", ReplyAction="http://tempuri.org/IEmailRegistration/GetEmailsByTagResponse")]
        ERS_Client_Console.RemoteService.Email[] GetEmailsByTag(string tag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailRegistrationChannel : ERS_Client_Console.RemoteService.IEmailRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailRegistrationClient : System.ServiceModel.ClientBase<ERS_Client_Console.RemoteService.IEmailRegistration>, ERS_Client_Console.RemoteService.IEmailRegistration {
        
        public EmailRegistrationClient() {
        }
        
        public EmailRegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailRegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailRegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailRegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public ERS_Client_Console.RemoteService.Email[] GetEmails() {
            return base.Channel.GetEmails();
        }
        
        public ERS_Client_Console.RemoteService.EmailFull GetEmailById(int _id) {
            return base.Channel.GetEmailById(_id);
        }
        
        public void AddEmail(ERS_Client_Console.RemoteService.EmailFull email) {
            base.Channel.AddEmail(email);
        }
        
        public void UpdateEmail(ERS_Client_Console.RemoteService.EmailFull email, string[] unrelatedTags) {
            base.Channel.UpdateEmail(email, unrelatedTags);
        }
        
        public ERS_Client_Console.RemoteService.Email[] GetEmailsByPeriod(System.DateTime date_left, System.DateTime date_right) {
            return base.Channel.GetEmailsByPeriod(date_left, date_right);
        }
        
        public ERS_Client_Console.RemoteService.Email[] GetEmailsByTo(string address) {
            return base.Channel.GetEmailsByTo(address);
        }
        
        public ERS_Client_Console.RemoteService.Email[] GetEmailsByFrom(string address) {
            return base.Channel.GetEmailsByFrom(address);
        }
        
        public ERS_Client_Console.RemoteService.Email[] GetEmailsByTag(string tag) {
            return base.Channel.GetEmailsByTag(tag);
        }
    }
}
